<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Rui</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b07dea51-05e2-4ab7-bda5-dbc309d770fd</testSuiteGuid>
   <testCaseLink>
      <guid>b2eb1800-2235-433d-9fc9-a1777fae5a85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Simple Examples/Login Test/Data-driven examples/Login with username and password as a default value of variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a11316c-738f-4e70-a8b5-63aaf81e1d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deb3cf4c-1dee-42c6-ab83-fae4778b5936</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
